import { useState } from 'react';
import { Link, useRouter } from 'expo-router';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import AppButton from '@/components/AppButton';
import Header from '@/components/Header';
import Screen from '@/components/Screen';
import { COLORS } from '@/constants/colors';
import { signUp } from '@/lib/auth';
import { setProfileRole, type UserRole } from '@/lib/profiles';
import { isSupabaseConfigured } from '@/lib/supabase';

export default function Register() {
  const router = useRouter(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [role, setRole] = useState<UserRole>('student'); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState(false); const [loading, setLoading] = useState(false);
  const submit = async () => { setError(null); if (!email.trim() || !password || !confirm) return setError('All fields are required.'); if (password !== confirm) return setError('Passwords do not match.'); if (password.length < 6) return setError('Password must be at least 6 characters.'); if (!isSupabaseConfigured) return setError('Add your Supabase configuration to .env first.'); setLoading(true); try { const { data, error: authError } = await signUp(email.trim(), password); if (authError) return setError(authError.message); if (data.user && data.session) await setProfileRole(data.user.id, role); if (data.session) router.replace('/(tabs)'); else setSuccess(true); } catch { setError('Unable to create the account. Please try again.'); } finally { setLoading(false); } };
  return <Screen><Header title="QR Attendance" /><View style={styles.heading}><Text style={styles.title}>Create account</Text><Text style={styles.subtitle}>Choose the role that matches how you will use attendance.</Text></View>{success ? <View style={styles.card}><Text style={styles.successTitle}>Check your email</Text><Text style={styles.subtitle}>Open the confirmation link sent to {email}, then return to sign in.</Text><Link href="/login" style={styles.link}>Back to sign in</Link></View> : <><Text style={styles.label}>I am a</Text><View style={styles.roles}>{(['student', 'teacher'] as UserRole[]).map((value) => <Pressable key={value} accessibilityRole="radio" accessibilityState={{ checked: role === value }} onPress={() => setRole(value)} style={[styles.role, role === value && styles.roleActive]}><Text style={[styles.roleText, role === value && styles.roleTextActive]}>{value[0].toUpperCase() + value.slice(1)}</Text></Pressable>)}</View><Text style={styles.label}>Email</Text><TextInput autoCapitalize="none" autoComplete="email" keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="your.email@school.edu" placeholderTextColor={COLORS.textSecondary} style={styles.input} /><Text style={styles.label}>Password</Text><TextInput secureTextEntry value={password} onChangeText={setPassword} placeholder="At least 6 characters" placeholderTextColor={COLORS.textSecondary} style={styles.input} /><Text style={styles.label}>Confirm password</Text><TextInput secureTextEntry value={confirm} onChangeText={setConfirm} placeholder="Re-enter your password" placeholderTextColor={COLORS.textSecondary} style={styles.input} />{error && <Text accessibilityRole="alert" style={styles.error}>{error}</Text>}<AppButton theme="primary" title="Sign Up" icon="person-add-outline" onPress={submit} loading={loading} /><Link href="/login" style={styles.link}>Already have an account? Sign in</Link></>}</Screen>;
}
const styles = StyleSheet.create({ heading: { marginTop: 30, marginBottom: 18 }, title: { fontSize: 28, fontWeight: '700', color: COLORS.textPrimary }, subtitle: { fontSize: 15, lineHeight: 22, color: COLORS.textSecondary, marginTop: 6 }, label: { fontSize: 14, fontWeight: '600', color: COLORS.textPrimary, marginTop: 12, marginBottom: 7 }, input: { minHeight: 50, borderWidth: 1, borderColor: COLORS.border, borderRadius: 10, backgroundColor: COLORS.card, paddingHorizontal: 14, fontSize: 16, color: COLORS.textPrimary }, roles: { flexDirection: 'row', gap: 10 }, role: { flex: 1, minHeight: 48, alignItems: 'center', justifyContent: 'center', borderRadius: 10, borderWidth: 1, borderColor: COLORS.border, backgroundColor: COLORS.card }, roleActive: { borderColor: COLORS.primary, backgroundColor: COLORS.surface }, roleText: { color: COLORS.textSecondary, fontWeight: '600' }, roleTextActive: { color: COLORS.textPrimary, fontWeight: '700' }, error: { color: COLORS.danger, marginVertical: 12 }, link: { color: COLORS.textPrimary, fontWeight: '700', fontSize: 15, marginTop: 14 }, card: { marginTop: 24, padding: 20, backgroundColor: COLORS.card, borderWidth: 1, borderColor: COLORS.border, borderRadius: 10 }, successTitle: { color: COLORS.textPrimary, fontSize: 20, fontWeight: '700' } });
