import { useCallback, useState } from 'react';
import { useFocusEffect } from 'expo-router';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import Screen from '@/components/Screen';
import { COLORS } from '@/constants/colors';
import { useAuth } from '@/lib/auth';
import { getAttendanceHistory, getTeacherEventAttendance, type AttendanceRecord, type TeacherEventAttendance } from '@/lib/attendance';
import { getProfile, type UserRole } from '@/lib/profiles';

export default function History() {
  const { user } = useAuth(); const [role, setRole] = useState<UserRole>('student'); const [records, setRecords] = useState<AttendanceRecord[]>([]); const [events, setEvents] = useState<TeacherEventAttendance[]>([]); const [openId, setOpenId] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useFocusEffect(useCallback(() => { let active = true; (async () => { if (!user) return; setLoading(true); setError(null); try { const profile = await getProfile(user.id); const nextRole = profile?.role ?? 'student'; if (!active) return; setRole(nextRole); if (nextRole === 'teacher') setEvents(await getTeacherEventAttendance(user.id)); else setRecords(await getAttendanceHistory(user.id)); } catch (e: any) { if (active) setError(e?.message ?? 'Could not load attendance.'); } finally { if (active) setLoading(false); } })(); return () => { active = false; }; }, [user?.id]));
  if (loading) return <Screen><ActivityIndicator color={COLORS.primary} style={styles.loader} /></Screen>;
  return <Screen><Text style={styles.title}>{role === 'teacher' ? 'Event attendance' : 'Attendance history'}</Text><Text style={styles.subtitle}>{role === 'teacher' ? 'Review the students recorded for each event.' : 'Your most recent verified scans appear first.'}</Text>{error && <Text style={styles.error}>{error}</Text>}{role === 'student' ? (records.length ? records.map((record) => <View style={styles.card} key={record.id}><Text style={styles.cardTitle}>{record.eventTitle}</Text><Text style={styles.meta}>{new Date(record.scannedAt).toLocaleString()}</Text></View>) : <Empty text="No attendance records yet. Scan an event QR code to get started." />) : (events.length ? events.map((event) => <View style={styles.card} key={event.eventId}><Pressable accessibilityRole="button" onPress={() => setOpenId(openId === event.eventId ? null : event.eventId)}><View style={styles.row}><View style={styles.grow}><Text style={styles.cardTitle}>{event.title}</Text><Text style={styles.meta}>{event.eventCode}</Text></View><Text style={styles.badge}>{event.attendees.length}</Text></View></Pressable>{openId === event.eventId && <View style={styles.attendees}>{event.attendees.length ? event.attendees.map((attendee) => <View key={`${attendee.studentId}-${attendee.scannedAt}`} style={styles.attendee}><Text style={styles.attendeeName}>{attendee.studentName ?? attendee.studentId.slice(0, 8)}</Text><Text style={styles.meta}>{new Date(attendee.scannedAt).toLocaleString()}</Text></View>) : <Text style={styles.meta}>No students recorded yet.</Text>}</View>}</View>) : <Empty text="No events yet. Create one from the Teacher tab." />)}</Screen>;
}
function Empty({ text }: { text: string }) { return <View style={styles.empty}><Text style={styles.meta}>{text}</Text></View>; }
const styles = StyleSheet.create({ loader: { marginTop: 80 }, title: { color: COLORS.textPrimary, fontSize: 26, fontWeight: '700' }, subtitle: { color: COLORS.textSecondary, fontSize: 15, lineHeight: 22, marginTop: 6, marginBottom: 20 }, error: { color: COLORS.danger, marginBottom: 12 }, card: { backgroundColor: COLORS.card, borderWidth: 1, borderColor: COLORS.border, borderRadius: 10, padding: 16, marginBottom: 12 }, cardTitle: { color: COLORS.textPrimary, fontSize: 17, fontWeight: '700' }, meta: { color: COLORS.textSecondary, fontSize: 13, lineHeight: 19, marginTop: 4 }, row: { flexDirection: 'row', alignItems: 'center', gap: 12 }, grow: { flex: 1 }, badge: { minWidth: 32, textAlign: 'center', overflow: 'hidden', color: COLORS.textOnPrimary, backgroundColor: COLORS.primary, borderRadius: 16, paddingVertical: 6, fontWeight: '700' }, attendees: { borderTopWidth: 1, borderTopColor: COLORS.border, marginTop: 14, paddingTop: 8 }, attendee: { paddingVertical: 8 }, attendeeName: { color: COLORS.textPrimary, fontWeight: '600' }, empty: { padding: 22, borderWidth: 1, borderColor: COLORS.border, borderRadius: 10, backgroundColor: COLORS.card } });
